#------------------------ Gadio ------------------------#
python vace/gradios/vace_ltx_demo.py

#------------------------ CLI ------------------------#
# txt2vid txt2vid
python vace/vace_ltx_inference.py --prompt "A sailboat with a white sail is navigating through rough, dark blue ocean waters under a stormy sky filled with thick, gray clouds. The boat tilts significantly as it rides the waves, and several seagulls fly around it. The scene is captured in real-life footage, with the camera angle shifting to follow the movement of the boat, emphasizing its struggle against the turbulent sea. The lighting is dim, reflecting the overcast conditions, and the overall tone is dramatic and intense."

# extension firstframe
python vace/vace_ltx_inference.py --src_video "benchmarks/VACE-Benchmark/assets/examples/firstframe/src_video.mp4" --src_mask "benchmarks/VACE-Benchmark/assets/examples/firstframe/src_mask.mp4" --prompt "A man in a black long-sleeve shirt is sitting inside a white vehicle, holding a walkie-talkie. He looks out the window with a serious expression. The camera gradually zooms in on his face, emphasizing his focused gaze. The background is blurred, but it appears to be an outdoor setting with some structures visible. The lighting is natural and bright, suggesting daytime. The scene is captured in real-life footage."

# repainting inpainting
python vace/vace_ltx_inference.py --src_video "benchmarks/VACE-Benchmark/assets/examples/inpainting/src_video.mp4" --src_mask "benchmarks/VACE-Benchmark/assets/examples/inpainting/src_mask.mp4" --prompt "A huge golden phoenix spread its wings and flew over the bustling city, its feathers shining brightly like flames, shimmering with warm radiance, and its wings spreading out majestic.The city below is filled with tall buildings adorned with colorful lights and billboards, creating a vibrant urban landscape. The camera follows the phoenix's flight from a high angle, capturing the grandeur of both the creature and the cityscape. The lighting is predominantly artificial, casting a warm glow on the buildings and streets, contrasting with the dark sky. The scene is a blend of animation and real-life footage, seamlessly integrating the fantastical element of the phoenix into a realistic city environment."

# repainting outpainting
python vace/vace_ltx_inference.py --src_video "benchmarks/VACE-Benchmark/assets/examples/outpainting/src_video.mp4" --src_mask "benchmarks/VACE-Benchmark/assets/examples/outpainting/src_mask.mp4" --prompt "The video begins with an aerial view of a grand, ancient gate illuminated by warm lights against the evening sky. The gate is surrounded by lush greenery and traditional Chinese architecture, including a prominent red-roofed building in the background. As the scene progresses, the gate's lighting intensifies, and a dynamic light show starts, featuring bright yellow and blue streaks emanating from the gate's archway, creating a visually striking effect. The light show continues to build in intensity, with more vibrant colors and patterns emerging. The camera angle remains static, capturing the entire spectacle from above. The lighting transitions from the natural dusk hues to the vivid, artificial lights of the display, enhancing the dramatic atmosphere. The scene is captured in real-life footage, showcasing the blend of historical architecture and modern light technology."

# control depth
python vace/vace_ltx_inference.py --src_video "benchmarks/VACE-Benchmark/assets/examples/depth/src_video.mp4" --prompt "In this enchanting animated scene, a group of young people gathers in a whimsical sky city to take a group photo, yet the photographer consistently captures the tender moments shared between couples. In the foreground, a young couple holds hands, while gazing into each other's eyes, smiles lighting up their faces. Surrounding them, vibrant hot air balloons float gracefully, and twinkling stars add a touch of magic to the atmosphere. The background features a dreamy sky, where warm sunlight filters through fluffy clouds, creating dappled shadows on the scene. The camera begins with a close-up, focusing on the couple's affectionate gestures, then slowly zooms out to reveal the warmth and vibrancy of the entire setting. The lighting is soft and romantic, casting a golden hue. The scene is captured in real-life footage"

# control flow
python vace/vace_ltx_inference.py --src_video "benchmarks/VACE-Benchmark/assets/examples/flow/src_video.mp4" --prompt "A bright red tomato was placed in a glass of milk, splashing water and creating ripples. The tomato sinks to the bottom of the glass, and the milk keeps shaking. The camera angle is a close-up shot, focusing on glass and milk. The bright and natural lighting highlights the pure white of the milk and the bright red of the tomatoes. This scene seems to be a real shot."

# control gray
python vace/vace_ltx_inference.py --src_video "benchmarks/VACE-Benchmark/assets/examples/gray/src_video.mp4" --prompt "A young woman with long, straight purple hair is standing in front of a lush autumn background. She is wearing an off-shoulder light yellow dress and smiling at the camera. The wind gently blows her hair to one side. The lighting is natural and bright, highlighting her features and the vibrant red and yellow leaves behind her. The scene is captured in real-life footage with a steady camera angle focusing on the woman's upper body."

# control pose
python vace/vace_ltx_inference.py --src_video "benchmarks/VACE-Benchmark/assets/examples/pose/src_video.mp4" --prompt "In a tropical celebration, a family gathers around a long table nestled under swaying palm trees, basking in the warmth of the sun. The table is laden with an array of exotic dishes, each colorful plate invitingly displayed. Elders engage in joyful conversations, their faces animated, while young adults raise their glasses in enthusiastic toasts. Children dash across the sandy beach. The background features a stunning azure ocean under a bright sun. The camera angle is in a dynamic mid-shot, fluidly capturing the moments of laughter and connection, while the lighting is bright and golden. The scene is presented in a realistic style."

# control scribble
python vace/vace_ltx_inference.py --src_video "benchmarks/VACE-Benchmark/assets/examples/scribble/src_video.mp4" --prompt "In this visually stunning scene, a vivid, neon-colored drone zips past the surreal West Xi'an ancient city wall at a low altitude, kicking up a cloud of glittering dust that catches the sunlight in a spectrum of colors. The camera swiftly shifts to a close-up of the bricks on the wall, where warm sunlight illuminates each stone, revealing intricate textures that tell tales of history. The background is rich with the majestic, timeworn wall, blending seamlessly into a dreamy atmosphere. The camera angle is at a dynamic angle, following the drone's swift movements with smooth transitions. The lighting is bright and vibrant, casting a magical glow. This scene is realized in striking animation."

# control layout
python vace/vace_ltx_inference.py --src_video "benchmarks/VACE-Benchmark/assets/examples/layout/src_video.mp4" --prompt "A small bird with a grey head, white chest, and orange tail feathers lands on a nest in a tree. The nest is made of twigs and leaves and contains three baby birds with their mouths open, waiting to be fed. The adult bird feeds the baby birds one by one, then takes off from the nest. The background is a blurred green forest, providing a natural setting for the scene. The camera angle is steady, focusing on the nest and the birds, capturing the intimate moment of feeding. The lighting is bright and natural, highlighting the colors of the birds and the nest. The scene appears to be real-life footage."

# reference face
python vace/vace_ltx_inference.py --src_ref_images "benchmarks/VACE-Benchmark/assets/examples/face/src_ref_image_1.png" --prompt "The video unfolds with an elderly man sporting pointy ears, his long silver hair cascading down, and a neatly trimmed goatee, wearing a vibrant, colorful robe over a golden shirt that radiates an aura of mystery and wisdom. The background is the interior of a magnificent palace, shining brilliantly. The camera dynamically rotates to capture this enchanting moment from various angles. The lighting is bright casting a warm glow. This scene seems to be a real shot."

# reference object
python vace/vace_ltx_inference.py --src_ref_images "benchmarks/VACE-Benchmark/assets/examples/object/src_ref_image_1.png" --prompt "Classic game character Mario is submerged in a turquoise underwater world, surrounded by vibrant corals and various tropical fish. He jumps excitedly upwards, striking his iconic cheerful pose while wearing a bright blue wetsuit and a red diving mask adorned with an “M” logo. His feet are equipped with sturdy diving boots. In the background, bubbles drift with the currents, revealing a large and friendly starfish nearby. The camera moves swiftly from the seabed upwards, capturing the moment he breaks the surface of the water. The lighting is bright and flowing. The scene combines animated and fantastical elements, creating a visually stunning experience."

# composition reference_anything
python vace/vace_ltx_inference.py --src_ref_images "benchmarks/VACE-Benchmark/assets/examples/reference_anything/src_ref_image_1.png,benchmarks/VACE-Benchmark/assets/examples/reference_anything/src_ref_image_2.png" --prompt "A man dressed as Superman stands confidently facing the camera, with a lively plush yellow duck perched on his shoulder. The man has neatly trimmed short hair and light stubble, while the duck features an orange beak and feet with slightly spread wings and legs positioned to maintain balance. The man's expression is serious and determined. He wears the iconic blue and red Superman costume, complete with a yellow "S" emblem on his chest and a cape flowing behind him. The background includes pedestrians walking by, adding to the scene's atmosphere. The camera is positioned at eye level, capturing the man's entire upper body. The lighting is bright and even, illuminating both the man and the duck. The scene appears to be real-life footage."

# composition swap_anything
python vace/vace_ltx_inference.py --src_video "benchmarks/VACE-Benchmark/assets/examples/swap_anything/src_video.mp4" --src_mask "benchmarks/VACE-Benchmark/assets/examples/swap_anything/src_mask.mp4" --src_ref_images "benchmarks/VACE-Benchmark/assets/examples/swap_anything/src_ref_image_1.png" --prompt "The video depicts a person with long, pale purple hair riding a horse across a vast grassland. The individual wears traditional attire featuring a white top and black pants, styled in an animation modeling approach, suggesting engagement in some outdoor activity or performance. The backdrop showcases magnificent mountains under a sky dotted with clouds, imparting a serene and expansive atmosphere. The camera angle is fixed throughout the video, focusing on the rider and his horse as they move through the landscape. The lighting is natural, highlighting the serene majesty of the scene. The scene is animated, capturing the tranquil beauty of the vast plains and towering mountains."

# composition expand_anything
python vace/vace_ltx_inference.py --src_video "benchmarks/VACE-Benchmark/assets/examples/expand_anything/src_video.mp4" --src_mask "benchmarks/VACE-Benchmark/assets/examples/expand_anything/src_mask.mp4" --src_ref_images "benchmarks/VACE-Benchmark/assets/examples/expand_anything/src_ref_image_1.png" --prompt "Set in the style of a classical oil painting, the scene unfolds along the bank of a river. At the center of the frame is a mature and elegant woman seated on a chair, wearing a flowing long dress. She gracefully lifts her hands from her lap to don a pair of red, heart-shaped sunglasses. The background features the tranquil river and lush surroundings, enhancing the serene atmosphere. The camera remains fixed, emphasizing the woman and her refined actions. The lighting is soft and warm, imitating the natural illumination typical of oil paintings. The scene is animated to replicate the timeless beauty and charm of classical art."
